package problems.p10_19;
/**
 * Highly divisible triangular number
 * Problem 12
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred divisors?
 * 
 * 
 * Answer:
 * 76576500
 * Completed on Mon, 25 Nov 2013, 00:05
 * http://projecteuler.net/problem=12
 * 
 * @author SBT
 *
 */
public class Problem12 {
	public static void main(String[] args) {
		int sum = 55;
		int currentNumber = 10;
		int limit, counter;
		do {
			sum += ++currentNumber;
			counter = 1;
			limit = (int) Math.sqrt(sum);
			for (int i = 2; i < limit; i++) {
				if (sum % i == 0) {
					counter++;
				}
			}
			counter *= 2;
			if (sum % limit == 0) {
				counter++;
			}
		} while (counter <= 500);
		System.out.println("Answer is : " + sum);
	}
}
