package problems;
/**
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * 
 * Answer:
 * 4613732
 * Completed on Sun, 24 Nov 2013, 16:10
 * http://projecteuler.net/problem=2
 * 
 * @author SBT
 *
 */

public class Problem2 {

	public static void main(String[] args) {
		int a = 1, b = 2;
		final int ceiling = 4000000;
		int sum = 0;
		for (; b < ceiling;) {
			sum += (b & 1) == 0 ? b : 0;
			b = a + b;
			a = b - a;
		}
		System.out.println("Answer is : " + sum);
	}

}
