# -*- coding: utf-8 -*-
'''
  Pentagon numbers
  Problem 44
  
  Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

  It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

  Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

  Answer: 5482660 Completed on Tue, 21 Oct 2014, 22:09
  https://projecteuler.net/problem=44
  
  @author Botu Sun
'''

import sys

limit = 200000000
numbers = []
map = {}
min = sys.maxint
def GeneratePentagonNumbers(start, limit):
  global map
  next = start * (3 * start - 1) / 2
  start += 1
  while (next <= limit):
    numbers.append(next)
    map[next] = True
    next = start * (3 * start - 1) / 2
    start += 1
  return start
  
GeneratePentagonNumbers(1, limit)

for i in xrange(1, len(numbers) / 2):
  for j in xrange(1, len(numbers) / 2):
    if i == j:
      continue
    if (map.has_key(numbers[i] + numbers[j]) and 
        map.has_key(abs(numbers[i] - numbers[j]))):
      if abs(numbers[i] - numbers[j]) < min:
        min = abs(numbers[i] - numbers[j])

print min